# fly.toml file generated for test-ex on 2022-10-08T07:35:51-07:00

app = "test-ex"
kill_signal = "SIGTERM"
kill_timeout = 5

[env]
  PHX_HOST = "embed.moe"
  PORT = "8080"

[http_service]
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
